```groovy
pipeline {
    agent any

    stages {

        stage('Terraform Init') {
            steps {
                dir('aws/local_state') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('aws/local_state') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('aws/local_state') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
```
