pipeline {
   agent any

stages {

    stage('Terraform Init') {
        steps {
            dir('aws/local_state') {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'terraform-aws']
                ]) {
                    sh 'terraform init'
                }
            }
        }
    }

    stage('Terraform Plan') {
        steps {
            dir('aws/local_state') {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'terraform-aws']
                ]) {
                    sh 'terraform plan'
                }
            }
        }
    }

    stage('Terraform Apply') {
        steps {
            dir('aws/local_state') {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'terraform-aws']
                ]) {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}

}
